# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Debug AAP-12160'
- task: BrowserStackAppUploader@0
  inputs:
    appPath: 'Wikipedia.apk'
- task: BrowserStackResults@0
- task: BrowserStackStopLocal@0
- task: Bash@3
  inputs:
    filePath: 'script.sh'
